# Hub with AKS node selector
apiVersion: v1
kind: Pod
metadata:
  name: selenium-hub
  labels:
    name: hub
spec:
  containers:
  - name: selenium-hub
    image: selenium/hub:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 4444
    livenessProbe:
        httpGet:
          path: /wd/hub/status
          port: 4444
        initialDelaySeconds: 30
        timeoutSeconds: 5
  nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
  tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
